### ISSUE TITLE
error at signup

### ISSUE THREAD

**Issue by decentraliser** [alan345/naperg#7]
Hi, 
an eror is thrown at signup, after entering a password:

Unhandled Rejection (TypeError): Cannot read property 'message' of undefined
(anonymous function)
src/components/user/auth/Signup.js:219
```
[  216 | 
  217 |     })
  218 |     .catch((e) => {
> 219 |       this.child._openSnackBar(e.graphQLErrors[0].message)
  220 |     })
  221 | 
  222 | }
```

**Comment by alan345** [comment]
Hi
It is because your server is not properly configured. The backend do not repond to frontend. Hence an error is dropped. 
When you connect to http://localhost:4000 do you have querirs, mutations and data?

**Comment by alan345** [comment]
Let me know if you need more help. I am closing this issue.
Thanks
Alan

**Comment by bathoorn** [comment]
I had this too in when testing the react  page using my phone.
Because now i could not go to http://localhost:3000 but had to use the ip of my laptop where all the services were running.

i had to replaced all the localhost references with ${window.location.hostname} in:
react/index.js
react/src/components/nav/ImageTemplate.js

After doing this the react client component can always find the server components as long as they all run on the same server.
